// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLUpdater is an autogenerated mock type for the URLUpdater type
type URLUpdater struct {
	mock.Mock
}

// UpdateURL provides a mock function with given fields: url, newAlias
func (_m *URLUpdater) UpdateURL(url string, newAlias string) (int64, error) {
	ret := _m.Called(url, newAlias)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return rf(url, newAlias)
	}
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(url, newAlias)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(url, newAlias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewURLUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewURLUpdater creates a new instance of URLUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewURLUpdater(t mockConstructorTestingTNewURLUpdater) *URLUpdater {
	mock := &URLUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
